import matplotlib.pyplot as plt
import matplotlib.patches as patches
qwerty_keyboard_layout = [
    [['ESC'], ['F1'], ['F2'], ['F3'], ['F4'], ['F5'], ['F6'], ['F7'], ['F8'], ['F9'], ['F10'], ['F11'], ['F12'], ['DELETE']],
    [['`', '~'], ['1', '!'], ['2', '@'], ['3', '#'], ['4', '$'], ['5', '%'], ['6', '^'], ['7', '&'], ['8', '*'], ['9', '('], ['0', ')'], ['-', '_'], ['=', '+'], ['BACKSPACE']],
    [['TAB'], ['q', 'Q'], ['w', 'W'], ['e', 'E'], ['r', 'R'], ['t', 'T'], ['y', 'Y'], ['u', 'U'], ['i', 'I'], ['o', 'O'], ['p', 'P'], ['[', '{'], [']', '}'], ['\\', '|']],
    [['CAPS'], ['a', 'A'], ['s', 'S'], ['d', 'D'], ['f', 'F'], ['g', 'G'], ['h', 'H'], ['j', 'J'], ['k', 'K'], ['l', 'L'], [';', ':'], ['\'', '"'], ['ENTER']],
    [['SHIFT'], ['z', 'Z'], ['x', 'X'], ['c', 'C'], ['v', 'V'], ['b', 'B'], ['n', 'N'], ['m', 'M'], [',', '<'], ['.', '>'], ['/', '?'], ['SHIFT']],
    [['CTRL'], ['FN'], ['WIN'], ['ALT'], ['SPACE'], ['ALT'], ['FN'], ['CTRL']]
]

qwerty_key_size = {
    'BACKSPACE':1.5,
    'TAB': 1.5,
    'CAPS': 1.75,
    'ENTER': 1.85,
    'SHIFT': 2.35,
    'SPACE': 6.35,
    'CTRL': 1.25,
    'WIN': 1.25,
    'ALT': 1.25,
    'FN':1.25,
    'DELETE':1.5
}
x = 0.2
ergodox_keyboard_layout = [
    # Left hand
    
        [['`','~'], ['1', '!'], ['2', '@'], ['3', '#'], ['4', '$'],['5', '%'],['DEL'], ['%4%'], ['DEL'],['6', '^'] , ['7', '&'], ['8', '*'], ['9', '('], ['0', ')'], ['=', '+']],
        [['TAB'], ['q', 'Q'], ['w', 'W'], ['e', 'E'], ['r', 'R'], ['t', 'T'], ['{','['],['%4%'],['}',']'], ['y', 'Y'], ['u', 'U'], ['i', 'I'], ['o', 'O'], ['p', 'P'], ['\\','|']],
        [['LSHIFT'], ['a', 'A'], ['s', 'S'], ['d', 'D'], ['f', 'F'], ['g', 'G'], ['_','-'],['%4%'], ['+','='],['h', 'H'], ['j', 'J'], ['k', 'K'], ['l', 'L'], [';', ':'], ['RSHIFT']],
        [['CTRL'], ['z', 'Z'], ['x', 'X'], ['c', 'C'], ['v', 'V'], ['b', 'B'],['%6.2%'],['n', 'N'], ['m', 'M'], [',', '<'], ['.', '>'], ['/', '?'], ['CTRL']],
        [['%0.5%'],['ALT'], ['CAPS'], ['PRT\nSC'], ['SCROLL\nLOCK'],['PAUSE'],['%8.4%'],['<-'], ['DOWN'], ['UP'], ['->'],['ALT']],
        # [],
        [[f'%{7.1+x}%'],['ESC'], ['WIN'],['%2%'],['WIN'], ['INS']],
        [[f'%{6+x}%'],['BKSPC'], ['DEL'],['HOME'],['%2%'],['PG UP'],['ENTER'], ['SPACE']],
        [[f'%{8.2+x}%'],['END'],['%2%'],['PG DN']]
]
ergodox_key_size = {
    'ESC': 1,'DEL':1,
    '1': 1, '2': 1, '3': 1, '4': 1, '5': 1, '6': 1,
    'TAB': 1.75, 'q': 1, 'w': 1, 'e': 1, 'r': 1, 't': 1, '-': 1,
    'CAPS': 1, 'a': 1, 's': 1, 'd': 1, 'f': 1, 'g': 1,
    'LSHIFT': 1.75, 'z': 1, 'x': 1, 'c': 1, 'v': 1, 'b': 1,
    'CTRL': 1.75, 'WIN': 1, 'ALT': 1.25, 'SPACE': 1,
    '^': 1, '7': 1, '8': 1, '9': 1, '0': 1, '=': 1.75, 'BACKSPACE': 1,
    'y': 1, 'u': 1, 'i': 1, 'o': 1, 'p': 1, '[': 1, ']': 1,
    'h': 1, 'j': 1, 'k': 1, 'l': 1, ';': 1, '\\': 1.75, 'ENTER': 1,
    'n': 1, 'm': 1, ',': 1, '.': 1, '/': 1, 'RSHIFT': 1.75,'`':1.75,
    'FN': 1.25, 'ALT': 1.25, 'WIN': 1,'PRT SC':1
}

keyboard_layouts = {
    'qwerty': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['r', 'R'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['t', 'T'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['y', 'Y'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['i', 'I'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['o', 'O'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['p', 'P'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['s', 'S'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['d', 'D'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['f', 'F'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['j', 'J'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['k', 'K'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['l', 'L'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\'', '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['n', 'N'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ],
    'dvorak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ["'", '"'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': [',', '<'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['.', '>'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['y', 'Y'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['f', 'F'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['g', 'G'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['c', 'C'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['r', 'R'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['l', 'L'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['/', '?'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['=', '+'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['o', 'O'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['u', 'U'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['i', 'I'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['d', 'D'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['h', 'H'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['t', 'T'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['n', 'N'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['s', 'S'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['-', '_'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': [';', ':'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['j', 'J'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['k', 'K'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['x', 'X'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['w', 'W'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['v', 'V'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['z', 'Z'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ],
    'colemak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['f', 'F'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['j', 'J'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['l', 'L'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['y', 'Y'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['r', 'R'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['s', 'S'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['t', 'T'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['d', 'D'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['n', 'N'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['e', 'E'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['i', 'I'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['o', 'O'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ["'", '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['k', 'K'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ]
}

key_layout = ergodox_keyboard_layout
key_size = ergodox_key_size
# key_layout = qwerty_keyboard_layout
# key_size = qwerty_key_size
y_start = 5
x_start = 0


ymax,ymin,xmax,xmin = 0,100,0,100
layout = {}
# layout[f'row{row}'] = {}
layout = []
# row_layout = layout[f'row{row}']
y_pos = y_start
y_pos = y_start    
for i in range(len(key_layout)):
    x_pos = x_start
    for j in range(len(key_layout[i])):
        el= {}
        chars = []
        c = key_layout[i][j][0]
        if c[0]=='%' and len(c)>1:
            x_pos+=float(c[1:-1])
            continue
        for k in key_layout[i][j]:
            chars.append(k)
        width = key_size.get(c, 1)
        el['chars'] = chars
        el['position'] = (x_pos,y_pos)
        el['dimensions'] = (width,1)
        test = 0
        for l in keyboard_layouts['qwerty']:
            ch = l['chars']
            if ch[0] == c :
                test=1
                k=l
                break
            if len(ch)>1 and ch[1] == c :
                test=1
                k=l
                break
        
        if test:
            el['side'] = k['side']
            el['start'] = k['start']
        else:
            el['side'] = 'L'
            el['start'] = c
            
        layout.append(el)
        
        xmax = max(xmax,x_pos+width)
        ymax = max(ymax,y_pos+1)
        xmin = min(xmin,x_pos)
        ymin = min(ymin,y_pos)
        x_pos += width +0.1
    y_pos -= 1.1   
print(layout)

def draw_keyboard(layout):
    fig, ax = plt.subplots(figsize=(15, 5))
    for key in layout:
        
        x, y = key['position']
        width,h = key['dimensions']
        chars = '\n'.join(key['chars'])  # Join the characters with newline for display
        
        # Create a rectangle for each key
        rect = plt.Rectangle((x, y), width, 1, edgecolor='black', facecolor='lightgray')
        ax.add_patch(rect)
        
        # Place the characters in the center of the key
        ax.text(x + width / 2, y + 0.5, chars, fontsize=10, ha='center', va='center')

    ax.set_xlim(xmin, xmax)  # Adjust based on the maximum x position
    ax.set_ylim(ymin, ymax)    # Adjust based on the maximum y position
    ax.axis('off')       # Turn off the axes
    plt.title('Ergodox Keyboard Layout', fontsize=16)
    plt.grid(False)
    plt.show()

draw_keyboard(layout)

d1 = 1.1
a1 = 0.2
a2 = 0.4
a3 = 0.2
keyboard_layouts = {
    'qwerty': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['r', 'R'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['t', 'T'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['y', 'Y'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['i', 'I'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['o', 'O'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['p', 'P'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['s', 'S'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['d', 'D'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['f', 'F'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['j', 'J'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['k', 'K'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['l', 'L'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\'', '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['n', 'N'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ],
    'dvorak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ["'", '"'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': [',', '<'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['.', '>'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['y', 'Y'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['f', 'F'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['g', 'G'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['c', 'C'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['r', 'R'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['l', 'L'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['/', '?'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ["'", '"'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['o', 'O'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['u', 'U'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['i', 'I'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['d', 'D'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['h', 'H'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['t', 'T'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['n', 'N'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['s', 'S'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['-', '_'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': [';', ':'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['j', 'J'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['k', 'K'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['x', 'X'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['w', 'W'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['v', 'V'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['z', 'Z'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ],
    'colemak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['f', 'F'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['j', 'J'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['l', 'L'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['y', 'Y'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['r', 'R'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['s', 'S'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['t', 'T'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['d', 'D'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['n', 'N'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['e', 'E'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['i', 'I'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['o', 'O'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ["'", '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['k', 'K'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ], 
    'ergodox':[{'chars': ['`', '~'], 'position': (0, 5), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.85, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.95, 5+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (4.050000000000001, 5+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (5.15, 5+a3), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (6.25, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['DEL'], 'position': (7.35, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['DEL'], 'position': (12.45, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['6', '^'], 'position': (13.549999999999999, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (14.649999999999999, 5+a3), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (15.749999999999998, 5+a2), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (16.849999999999998, 5+a1), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (17.95, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (19.05, 5), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 3.9), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.85, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.95, 3.9+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (4.050000000000001, 3.9+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['r', 'R'], 'position': (5.15, 3.9+a3), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['t', 'T'], 'position': (6.25, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['{', '['], 'position': (7.35, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['}', ']'], 'position': (12.45, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['y', 'Y'], 'position': (13.549999999999999, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (14.649999999999999, 3.9+a3), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['i', 'I'], 'position': (15.749999999999998, 3.9+a2), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['o', 'O'], 'position': (16.849999999999998, 3.9+a1), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['p', 'P'], 'position': (17.95, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (19.05, 3.9), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 2.8), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['s', 'S'], 'position': (2.95, 2.8+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['d', 'D'], 'position': (4.050000000000001, 2.8+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['f', 'F'], 'position': (5.15, 2.8+a3), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.25, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['_', '-'], 'position': (7.35, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['+', '='], 'position': (12.45, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['h', 'H'], 'position': (13.549999999999999, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['j', 'J'], 'position': (14.649999999999999, 2.8+a3), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['k', 'K'], 'position': (15.749999999999998, 2.8+a2), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['l', 'L'], 'position': (16.849999999999998, 2.8+a1), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (17.95, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (19.05, 2.8), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, 1.6999999999999997), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (1.85, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (2.95, 1.6999999999999997+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.050000000000001, 1.6999999999999997+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.15, 1.6999999999999997+a3), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.25, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['n', 'N'], 'position': (13.55, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (14.65, 1.6999999999999997+a3), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (15.75, 1.6999999999999997+a2), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (16.85, 1.6999999999999997+a1), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (17.950000000000003, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (19.050000000000004, 1.6999999999999997), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['ALT'], 'position': (0.5, 0.5999999999999996), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['CAPS'], 'position': (1.85, 0.5999999999999996), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['PRT\nSC'], 'position': (2.95, 0.5999999999999996+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 'PRT\nSC'},
        {'chars': ['SCROLL\nLOCK'], 'position': (4.050000000000001, 0.5999999999999996+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'SCROLL\nLOCK'},
        {'chars': ['PAUSE'], 'position': (5.15, 0.5999999999999996+a3), 'dimensions': (1, 1), 'side': 'L', 'start': 'PAUSE'},
        {'chars': ['<-'], 'position': (14.65, 0.5999999999999996+a3), 'dimensions': (1, 1), 'side': 'L', 'start': '<-'},
        {'chars': ['DOWN'], 'position': (15.75, 0.5999999999999996+a2), 'dimensions': (1, 1), 'side': 'L', 'start': 'DOWN'},
        {'chars': ['UP'], 'position': (16.85, 0.5999999999999996+a1), 'dimensions': (1, 1), 'side': 'L', 'start': 'UP'},
        {'chars': ['->'], 'position': (17.950000000000003, 0.5999999999999996), 'dimensions': (1, 1), 'side': 'L', 'start': '->'},
        {'chars': ['ALT'], 'position': (19.050000000000004, 0.5999999999999996), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['ESC'], 'position': (7.3, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['WIN'], 'position': (8.4, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['WIN'], 'position': (11.5, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['INS'], 'position': (12.6, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'INS'},
        {'chars': ['BKSPC'], 'position': (6.2, -1.6000000000000005-d1), 'dimensions': (1, 1+d1), 'side': 'L', 'start': 'BKSPC'},
        {'chars': ['DEL'], 'position': (7.300000000000001, -1.6000000000000005-d1), 'dimensions': (1, 1+d1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['HOME'], 'position': (8.4, -1.6000000000000005), 'dimensions': (1, 1), 'side': 'L', 'start': 'HOME'},
        {'chars': ['PG UP'], 'position': (11.5, -1.6000000000000005), 'dimensions': (1, 1), 'side': 'L', 'start': 'PG UP'},
        {'chars': ['ENTER'], 'position': (12.6, -1.6000000000000005-d1), 'dimensions': (1, 1+d1), 'side': 'R', 'start': ';'},
        {'chars': ['SPACE'], 'position': (13.7, -1.6000000000000005-d1), 'dimensions': (1, 1+d1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['END'], 'position': (8.399999999999999, -2.7000000000000006), 'dimensions': (1, 1), 'side': 'L', 'start': 'END'},
        {'chars': ['PG DN'], 'position': (11.499999999999998, -2.7000000000000006), 'dimensions': (1, 1), 'side': 'L', 'start': 'PG DN'}]
}