keyboard_layouts = {
    'qwerty': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['r', 'R'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['t', 'T'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['y', 'Y'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['i', 'I'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['o', 'O'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['p', 'P'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['s', 'S'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['d', 'D'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['f', 'F'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['j', 'J'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['k', 'K'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['l', 'L'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\'', '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['n', 'N'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'f'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'f'}
    ],
    'dvorak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'o'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'e'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 't'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 's'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': 's'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ["'", '"'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': [',', '<'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'o'},
        {'chars': ['.', '>'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'e'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['y', 'Y'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['f', 'F'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['g', 'G'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['c', 'C'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 't'},
        {'chars': ['r', 'R'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['l', 'L'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'c'},
        {'chars': ['/', '?'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'c'},
        {'chars': ['=', '+'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'c'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'c'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['o', 'O'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'o'},
        {'chars': ['e', 'E'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'e'},
        {'chars': ['u', 'U'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['i', 'I'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['d', 'D'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['h', 'H'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['t', 'T'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 't'},
        {'chars': ['n', 'N'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['s', 'S'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 's'},
        {'chars': ['-', '_'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 's'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': 's'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': [';', ':'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'o'},
        {'chars': ['j', 'J'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'e'},
        {'chars': ['k', 'K'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['x', 'X'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'u'},
        {'chars': ['b', 'B'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'h'},
        {'chars': ['w', 'W'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 't'},
        {'chars': ['v', 'V'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['z', 'Z'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 's'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': 's'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'o'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'u'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 'u'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 'u'}
    ],
    'colemak': [
        {'chars': ['ESC'], 'position': (0, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F1'], 'position': (1.1, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F2'], 'position': (2.2, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F3'], 'position': (3.3, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F4'], 'position': (4.4, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F5'], 'position': (5.5, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F6'], 'position': (6.6, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['F7'], 'position': (7.7, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['F8'], 'position': (8.8, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['F9'], 'position': (9.9, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['F10'], 'position': (11.0, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['F11'], 'position': (12.1, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['F12'], 'position': (13.2, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['DELETE'], 'position': (14.3, 5), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['`', '~'], 'position': (0, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.1, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.2, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'r'},
        {'chars': ['3', '#'], 'position': (3.3, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['4', '$'], 'position': (4.4, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['5', '%'], 'position': (5.5, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['6', '^'], 'position': (6.6, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['7', '&'], 'position': (7.7, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['8', '*'], 'position': (8.8, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['9', '('], 'position': (9.9, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (11.0, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'i'},
        {'chars': ['-', '_'], 'position': (12.1, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'i'},
        {'chars': ['=', '+'], 'position': (13.2, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['BACKSPACE'], 'position': (14.3, 3.9), 'dimensions': (1.5, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['TAB'], 'position': (0, 2.8), 'dimensions': (1.5, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.6, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.7, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'r'},
        {'chars': ['f', 'F'], 'position': (3.8, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['p', 'P'], 'position': (4.9, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['g', 'G'], 'position': (6.0, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['j', 'J'], 'position': (7.1, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['l', 'L'], 'position': (8.2, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['u', 'U'], 'position': (9.3, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'e'},
        {'chars': ['y', 'Y'], 'position': (10.4, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'i'},
        {'chars': [';', ':'], 'position': (11.5, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['[', '{'], 'position': (12.6, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': [']', '}'], 'position': (13.7, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['\\', '|'], 'position': (14.8, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['CAPS'], 'position': (0, 1.7), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['r', 'R'], 'position': (2.95, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 'r'},
        {'chars': ['s', 'S'], 'position': (4.05, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['t', 'T'], 'position': (5.15, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['d', 'D'], 'position': (6.25, 1.7), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['h', 'H'], 'position': (7.35, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['n', 'N'], 'position': (8.45, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['e', 'E'], 'position': (9.55, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'e'},
        {'chars': ['i', 'I'], 'position': (10.65, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'i'},
        {'chars': ['o', 'O'], 'position': (11.75, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ["'", '"'], 'position': (12.85, 1.7), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['ENTER'], 'position': (13.95, 1.7), 'dimensions': (1.85, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['LSHIFT'], 'position': (0, 0.6), 'dimensions': (2.35, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (2.45, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (3.55, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 'r'},
        {'chars': ['c', 'C'], 'position': (4.65, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['v', 'V'], 'position': (5.75, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['b', 'B'], 'position': (6.85, 0.6), 'dimensions': (1, 1), 'side': 'L', 'start': 't'},
        {'chars': ['k', 'K'], 'position': (7.95, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': ['m', 'M'], 'position': (9.05, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'n'},
        {'chars': [',', '<'], 'position': (10.15, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'e'},
        {'chars': ['.', '>'], 'position': (11.25, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'i'},
        {'chars': ['/', '?'], 'position': (12.35, 0.6), 'dimensions': (1, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['RSHIFT'], 'position': (13.45, 0.6), 'dimensions': (2.35, 1), 'side': 'R', 'start': 'o'},
        {'chars': ['CTRL'], 'position': (0, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['FN'], 'position': (1.35, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['WIN'], 'position': (2.7, -0.5000000000000004), 'dimensions': (1.25,1),'side': 'L', 'start':'a'},
        {'chars': ['ALT'], 'position': (4.05, -0.5), 'dimensions': (1.25, 1), 'side': 'L', 'start': 'r'},
        {'chars': ['SPACE'], 'position': (5.4, -0.5), 'dimensions': (6.35, 1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['ALT'], 'position': (11.85, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 't'},
        {'chars': ['FN'], 'position': (13.2, -0.5), 'dimensions': (1.25, 1),'side': 'R', 'start': 't'},
        {'chars': ['CTRL'], 'position': (14.55, -0.5), 'dimensions': (1.25, 1), 'side': 'R', 'start': 't'}
    ], 
    'ergodox':[{'chars': ['`', '~'], 'position': (0, 5), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['1', '!'], 'position': (1.85, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['2', '@'], 'position': (2.95, 5+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['3', '#'], 'position': (4.050000000000001, 5+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['4', '$'], 'position': (5.15, 5+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['5', '%'], 'position': (6.25, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['DEL'], 'position': (7.35, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['DEL'], 'position': (12.45, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['6', '^'], 'position': (13.549999999999999, 5), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['7', '&'], 'position': (14.649999999999999, 5+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['8', '*'], 'position': (15.749999999999998, 5+0.4), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['9', '('], 'position': (16.849999999999998, 5+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['0', ')'], 'position': (17.95, 5), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['=', '+'], 'position': (19.05, 5), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['TAB'], 'position': (0, 3.9), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['q', 'Q'], 'position': (1.85, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['w', 'W'], 'position': (2.95, 3.9+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['e', 'E'], 'position': (4.050000000000001, 3.9+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['r', 'R'], 'position': (5.15, 3.9+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['t', 'T'], 'position': (6.25, 3.9), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['{', '['], 'position': (7.35, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['}', ']'], 'position': (12.45, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['y', 'Y'], 'position': (13.549999999999999, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['u', 'U'], 'position': (14.649999999999999, 3.9+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['i', 'I'], 'position': (15.749999999999998, 3.9+0.4), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['o', 'O'], 'position': (16.849999999999998, 3.9+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['p', 'P'], 'position': (17.95, 3.9), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['\\', '|'], 'position': (19.05, 3.9), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['LSHIFT'], 'position': (0, 2.8), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['a', 'A'], 'position': (1.85, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['s', 'S'], 'position': (2.95, 2.8+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['d', 'D'], 'position': (4.050000000000001, 2.8+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['f', 'F'], 'position': (5.15, 2.8+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['g', 'G'], 'position': (6.25, 2.8), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['-', '_'], 'position': (7.35, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ["'", '"'], 'position': (12.45, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['h', 'H'], 'position': (13.549999999999999, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['j', 'J'], 'position': (14.649999999999999, 2.8+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['k', 'K'], 'position': (15.749999999999998, 2.8+0.4), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['l', 'L'], 'position': (16.849999999999998, 2.8+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': [';', ':'], 'position': (17.95, 2.8), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['RSHIFT'], 'position': (19.05, 2.8), 'dimensions': (1.75, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (0, 1.6999999999999997), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['z', 'Z'], 'position': (1.85, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['x', 'X'], 'position': (2.95, 1.6999999999999997+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 's'},
        {'chars': ['c', 'C'], 'position': (4.050000000000001, 1.6999999999999997+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'd'},
        {'chars': ['v', 'V'], 'position': (5.15, 1.6999999999999997+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['b', 'B'], 'position': (6.25, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'L', 'start': 'f'},
        {'chars': ['n', 'N'], 'position': (13.55, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': ['m', 'M'], 'position': (14.65, 1.6999999999999997+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'j'},
        {'chars': [',', '<'], 'position': (15.75, 1.6999999999999997+0.4), 'dimensions': (1, 1), 'side': 'R', 'start': 'k'},
        {'chars': ['.', '>'], 'position': (16.85, 1.6999999999999997+0.2), 'dimensions': (1, 1), 'side': 'R', 'start': 'l'},
        {'chars': ['/', '?'], 'position': (17.950000000000003, 1.6999999999999997), 'dimensions': (1, 1), 'side': 'R', 'start': ';'},
        {'chars': ['CTRL'], 'position': (19.050000000000004, 1.6999999999999997), 'dimensions': (1.75, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['ALT'], 'position': (0.5, 0.5999999999999996), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['CAPS'], 'position': (1.85, 0.5999999999999996), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['PRT\nSC'], 'position': (2.95, 0.5999999999999996+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'PRT\nSC'},
        {'chars': ['SCROLL\nLOCK'], 'position': (4.050000000000001, 0.5999999999999996+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'SCROLL\nLOCK'},
        {'chars': ['PAUSE'], 'position': (5.15, 0.5999999999999996+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'PAUSE'},
        {'chars': ['<-'], 'position': (14.65, 0.5999999999999996+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': '<-'},
        {'chars': ['DOWN'], 'position': (15.75, 0.5999999999999996+0.4), 'dimensions': (1, 1), 'side': 'L', 'start': 'DOWN'},
        {'chars': ['UP'], 'position': (16.85, 0.5999999999999996+0.2), 'dimensions': (1, 1), 'side': 'L', 'start': 'UP'},
        {'chars': ['->'], 'position': (17.950000000000003, 0.5999999999999996), 'dimensions': (1, 1), 'side': 'L', 'start': '->'},
        {'chars': ['ALT'], 'position': (19.050000000000004, 0.5999999999999996), 'dimensions': (1.25, 1), 'side': 'L', 'start': 's'},
        {'chars': ['ESC'], 'position': (7.3, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['WIN'], 'position': (8.4, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['WIN'], 'position': (11.5, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'a'},
        {'chars': ['INS'], 'position': (12.6, -0.5000000000000004), 'dimensions': (1, 1), 'side': 'L', 'start': 'INS'},
        {'chars': ['BKSPC'], 'position': (6.2, -1.6000000000000005-1.1), 'dimensions': (1, 1+1.1), 'side': 'L', 'start': 'BKSPC'},
        {'chars': ['DEL'], 'position': (7.300000000000001, -1.6000000000000005-1.1), 'dimensions': (1, 1+1.1), 'side': 'L', 'start': 'DEL'},
        {'chars': ['HOME'], 'position': (8.4, -1.6000000000000005), 'dimensions': (1, 1), 'side': 'L', 'start': 'HOME'},
        {'chars': ['PG UP'], 'position': (11.5, -1.6000000000000005), 'dimensions': (1, 1), 'side': 'L', 'start': 'PG UP'},
        {'chars': ['ENTER'], 'position': (12.6, -1.6000000000000005-1.1), 'dimensions': (1, 1+1.1), 'side': 'R', 'start': 'SPACE'},
        {'chars': ['SPACE'], 'position': (13.7, -1.6000000000000005-1.1), 'dimensions': (1, 1+1.1), 'side': 'L', 'start': 'SPACE'},
        {'chars': ['END'], 'position': (8.399999999999999, -2.7000000000000006), 'dimensions': (1, 1), 'side': 'L', 'start': 'END'},
        {'chars': ['PG DN'], 'position': (11.499999999999998, -2.7000000000000006), 'dimensions': (1, 1), 'side': 'L', 'start': 'PG DN'}]
}